export enum type {
  POOL_UPGRADE = '109',
  NODE_UPGRADE = '110',
  POOL_CONFIG = '111',
  AUTH_RULE = '120',
  AUTH_RULES = '122',
  TRANSACTION_AUTHR_AGREEMENT = '4',
  TRANSACTION_AUTHR_AGREEMENT_AML = '5',
}
