export enum type {
  GET_TXN = '3',
  GET_TXN_AUTHOR_AGREEMENT = '6',
  GET_TXN_AUTHOR_AGREEMENT_AML = '7',
  GET_ATTR = '104',
  GET_NYM = '105',
  GET_SCHEMA = '107',
  GET_CLAIM_DEF = '108',
  GET_REVOC_REG_DEF = '115',
  GET_REVOC_REG = '116',
  GET_REVOC_REG_DELTA = '117',
  GET_AUTH_RULE = '121',
  GET_CONTEXT = '300',
}
